const std = @import("std");
const mem = std.mem;
const Allocator = mem.Allocator;
const VoltFile = @import("volt_file.zig");

// ── API Documentation Generator ─────────────────────────────────────────
// Generates Markdown and HTML documentation from collections of .volt files.
// Creates endpoint reference docs with method, URL, headers, body examples,
// and test expectations.

pub const HeaderDoc = struct {
    name: []const u8,
    value: []const u8,
};

pub const DocEntry = struct {
    name: []const u8,
    method: []const u8,
    url: []const u8,
    description: ?[]const u8 = null,
    headers: std.ArrayList(HeaderDoc),
    body_type: []const u8,
    body_example: ?[]const u8 = null,
    auth_type: []const u8,
    tests: std.ArrayList([]const u8),

    pub fn init(allocator: Allocator) DocEntry {
        return .{
            .name = "",
            .method = "GET",
            .url = "",
            .headers = std.ArrayList(HeaderDoc).init(allocator),
            .body_type = "none",
            .auth_type = "none",
            .tests = std.ArrayList([]const u8).init(allocator),
        };
    }

    pub fn deinit(self: *DocEntry) void {
        self.headers.deinit();
        self.tests.deinit();
    }
};

/// Generate Markdown documentation from a list of parsed requests
pub fn generateMarkdown(allocator: Allocator, entries: []const DocEntry, title: []const u8) ![]const u8 {
    var buf = std.ArrayList(u8).init(allocator);
    const writer = buf.writer();

    try writer.print("# API Documentation: {s}\n\n", .{title});
    try writer.writeAll("Generated by Volt API Client\n\n");
    try writer.writeAll("---\n\n");

    // Table of contents
    if (entries.len > 1) {
        try writer.writeAll("## Table of Contents\n\n");
        for (entries, 0..) |entry, i| {
            try writer.print("{d}. **{s}** `{s}`\n", .{ i + 1, entry.method, entry.url });
        }
        try writer.writeAll("\n---\n\n");
    }

    for (entries) |entry| {
        // Section heading
        try writer.print("## {s} {s}\n\n", .{ entry.method, entry.url });

        // File name
        if (entry.name.len > 0) {
            try writer.print("**File:** `{s}`\n\n", .{entry.name});
        }

        // Description
        if (entry.description) |desc| {
            try writer.print("{s}\n\n", .{desc});
        }

        // Authentication
        if (!mem.eql(u8, entry.auth_type, "none")) {
            try writer.print("**Authentication:** {s}\n\n", .{entry.auth_type});
        }

        // Headers table
        if (entry.headers.items.len > 0) {
            try writer.writeAll("### Headers\n\n");
            try writer.writeAll("| Header | Value |\n");
            try writer.writeAll("|--------|-------|\n");
            for (entry.headers.items) |h| {
                try writer.print("| {s} | {s} |\n", .{ h.name, h.value });
            }
            try writer.writeAll("\n");
        }

        // Body
        if (entry.body_example) |body| {
            try writer.writeAll("### Body\n\n");
            try writer.print("**Type:** `{s}`\n\n", .{entry.body_type});
            // Determine code block language
            const lang = if (mem.eql(u8, entry.body_type, "json"))
                "json"
            else if (mem.eql(u8, entry.body_type, "xml"))
                "xml"
            else
                "";
            try writer.print("```{s}\n{s}\n```\n\n", .{ lang, body });
        }

        // Tests
        if (entry.tests.items.len > 0) {
            try writer.writeAll("### Tests\n\n");
            for (entry.tests.items) |t| {
                try writer.print("- {s}\n", .{t});
            }
            try writer.writeAll("\n");
        }

        try writer.writeAll("---\n\n");
    }

    // Footer
    try writer.print("*{d} endpoint(s) documented.*\n", .{entries.len});

    return buf.toOwnedSlice();
}

/// Generate HTML documentation (wraps markdown-like content in HTML template)
pub fn generateHtml(allocator: Allocator, entries: []const DocEntry, title: []const u8) ![]const u8 {
    var buf = std.ArrayList(u8).init(allocator);
    const writer = buf.writer();

    // HTML head with inline CSS
    try writer.writeAll("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
    try writer.writeAll("  <meta charset=\"UTF-8\">\n");
    try writer.writeAll("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    try writer.print("  <title>{s} - API Documentation</title>\n", .{title});
    try writer.writeAll("  <style>\n");
    try writer.writeAll("    * { margin: 0; padding: 0; box-sizing: border-box; }\n");
    try writer.writeAll("    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;\n");
    try writer.writeAll("      background: #1a1a2e; color: #e0e0e0; line-height: 1.6; padding: 2rem; }\n");
    try writer.writeAll("    .container { max-width: 960px; margin: 0 auto; }\n");
    try writer.writeAll("    h1 { color: #00d4ff; margin-bottom: 0.5rem; font-size: 2rem; }\n");
    try writer.writeAll("    h2 { color: #ffffff; margin: 1.5rem 0 0.5rem; font-size: 1.4rem; }\n");
    try writer.writeAll("    h3 { color: #b0b0b0; margin: 1rem 0 0.5rem; font-size: 1.1rem; }\n");
    try writer.writeAll("    .subtitle { color: #888; margin-bottom: 2rem; }\n");
    try writer.writeAll("    .endpoint { background: #16213e; border-radius: 8px; padding: 1.5rem;\n");
    try writer.writeAll("      margin-bottom: 1.5rem; border: 1px solid #2a2a4a; }\n");
    try writer.writeAll("    .method-badge { display: inline-block; padding: 0.2rem 0.6rem;\n");
    try writer.writeAll("      border-radius: 4px; font-weight: bold; font-size: 0.85rem;\n");
    try writer.writeAll("      margin-right: 0.5rem; }\n");
    try writer.writeAll("    .method-GET { background: #2ecc71; color: #000; }\n");
    try writer.writeAll("    .method-POST { background: #3498db; color: #fff; }\n");
    try writer.writeAll("    .method-PUT { background: #f39c12; color: #000; }\n");
    try writer.writeAll("    .method-PATCH { background: #e67e22; color: #000; }\n");
    try writer.writeAll("    .method-DELETE { background: #e74c3c; color: #fff; }\n");
    try writer.writeAll("    .method-HEAD { background: #9b59b6; color: #fff; }\n");
    try writer.writeAll("    .method-OPTIONS { background: #95a5a6; color: #000; }\n");
    try writer.writeAll("    .url { font-family: 'Fira Code', monospace; color: #00d4ff; }\n");
    try writer.writeAll("    table { width: 100%; border-collapse: collapse; margin: 0.5rem 0; }\n");
    try writer.writeAll("    th, td { text-align: left; padding: 0.5rem; border-bottom: 1px solid #2a2a4a; }\n");
    try writer.writeAll("    th { color: #888; font-size: 0.85rem; text-transform: uppercase; }\n");
    try writer.writeAll("    code { background: #0f3460; padding: 0.2rem 0.4rem; border-radius: 3px;\n");
    try writer.writeAll("      font-family: 'Fira Code', monospace; font-size: 0.9rem; }\n");
    try writer.writeAll("    pre { background: #0f3460; padding: 1rem; border-radius: 6px;\n");
    try writer.writeAll("      overflow-x: auto; margin: 0.5rem 0; }\n");
    try writer.writeAll("    pre code { background: none; padding: 0; }\n");
    try writer.writeAll("    .test-item { padding: 0.25rem 0; }\n");
    try writer.writeAll("    .test-check { color: #2ecc71; margin-right: 0.5rem; }\n");
    try writer.writeAll("    .auth-badge { background: #e74c3c; color: #fff; padding: 0.15rem 0.5rem;\n");
    try writer.writeAll("      border-radius: 3px; font-size: 0.8rem; }\n");
    try writer.writeAll("    .filename { color: #666; font-size: 0.85rem; font-style: italic; }\n");
    try writer.writeAll("    hr { border: none; border-top: 1px solid #2a2a4a; margin: 2rem 0; }\n");
    try writer.writeAll("    .footer { color: #555; font-size: 0.85rem; margin-top: 2rem; text-align: center; }\n");
    try writer.writeAll("  </style>\n");
    try writer.writeAll("</head>\n<body>\n");
    try writer.writeAll("  <div class=\"container\">\n");

    // Title
    try writer.print("    <h1>{s}</h1>\n", .{title});
    try writer.writeAll("    <p class=\"subtitle\">Generated by Volt API Client</p>\n");
    try writer.writeAll("    <hr>\n\n");

    // Entries
    for (entries) |entry| {
        try writer.writeAll("    <div class=\"endpoint\">\n");

        // Method badge + URL
        try writer.print("      <h2><span class=\"method-badge method-{s}\">{s}</span> ", .{ entry.method, entry.method });
        try writer.print("<span class=\"url\">{s}</span></h2>\n", .{entry.url});

        // Filename
        if (entry.name.len > 0) {
            try writer.print("      <p class=\"filename\">{s}</p>\n", .{entry.name});
        }

        // Description
        if (entry.description) |desc| {
            try writer.print("      <p>{s}</p>\n", .{desc});
        }

        // Auth
        if (!mem.eql(u8, entry.auth_type, "none")) {
            try writer.print("      <p><span class=\"auth-badge\">{s}</span></p>\n", .{entry.auth_type});
        }

        // Headers
        if (entry.headers.items.len > 0) {
            try writer.writeAll("      <h3>Headers</h3>\n");
            try writer.writeAll("      <table>\n");
            try writer.writeAll("        <tr><th>Header</th><th>Value</th></tr>\n");
            for (entry.headers.items) |h| {
                try writer.print("        <tr><td><code>{s}</code></td><td><code>{s}</code></td></tr>\n", .{ h.name, h.value });
            }
            try writer.writeAll("      </table>\n");
        }

        // Body
        if (entry.body_example) |body| {
            try writer.writeAll("      <h3>Body</h3>\n");
            try writer.print("      <p>Type: <code>{s}</code></p>\n", .{entry.body_type});
            try writer.writeAll("      <pre><code>");
            // HTML-escape the body
            for (body) |c| {
                switch (c) {
                    '<' => try writer.writeAll("&lt;"),
                    '>' => try writer.writeAll("&gt;"),
                    '&' => try writer.writeAll("&amp;"),
                    '"' => try writer.writeAll("&quot;"),
                    else => try writer.writeByte(c),
                }
            }
            try writer.writeAll("</code></pre>\n");
        }

        // Tests
        if (entry.tests.items.len > 0) {
            try writer.writeAll("      <h3>Tests</h3>\n");
            for (entry.tests.items) |t| {
                try writer.print("      <div class=\"test-item\"><span class=\"test-check\">&#10003;</span>{s}</div>\n", .{t});
            }
        }

        try writer.writeAll("    </div>\n\n");
    }

    // Footer
    try writer.print("    <p class=\"footer\">{d} endpoint(s) documented</p>\n", .{entries.len});
    try writer.writeAll("  </div>\n");
    try writer.writeAll("</body>\n</html>\n");

    return buf.toOwnedSlice();
}

/// Build DocEntry from a VoltRequest
pub fn fromRequest(allocator: Allocator, request: *const VoltFile.VoltRequest, filename: []const u8) !DocEntry {
    var entry = DocEntry.init(allocator);

    entry.name = try allocator.dupe(u8, filename);
    entry.method = request.method.toString(); // comptime string literal, safe
    entry.url = try allocator.dupe(u8, request.url);
    entry.body_type = request.body_type.toString(); // comptime string literal, safe
    entry.body_example = if (request.body) |b| try allocator.dupe(u8, b) else null;
    entry.auth_type = request.auth.type.toString(); // comptime string literal, safe

    // Copy headers (dupe strings since request will be freed)
    for (request.headers.items) |h| {
        try entry.headers.append(.{
            .name = try allocator.dupe(u8, h.name),
            .value = try allocator.dupe(u8, h.value),
        });
    }

    // Build test descriptions
    for (request.tests.items) |t| {
        const desc = try std.fmt.allocPrint(allocator, "{s} {s} {s}", .{ t.field, t.operator, t.value });
        try entry.tests.append(desc);
    }

    return entry;
}

/// Scan a directory and generate Markdown docs for all .volt files found
pub fn generateDocsFromDir(allocator: Allocator, dir_path: []const u8, title: []const u8) ![]const u8 {
    var entries = std.ArrayList(DocEntry).init(allocator);
    defer {
        for (entries.items) |*e| {
            // Free owned strings
            allocator.free(e.name);
            allocator.free(e.url);
            if (e.body_example) |b| allocator.free(b);
            for (e.headers.items) |h| {
                allocator.free(h.name);
                allocator.free(h.value);
            }
            for (e.tests.items) |t| {
                allocator.free(t);
            }
            e.deinit();
        }
        entries.deinit();
    }

    // Open directory and scan for .volt files
    var dir = std.fs.cwd().openDir(dir_path, .{ .iterate = true }) catch {
        // If directory can't be opened, return error description as markdown
        var buf = std.ArrayList(u8).init(allocator);
        const writer = buf.writer();
        try writer.print("# API Documentation: {s}\n\n", .{title});
        try writer.writeAll("Error: Could not open the specified directory.\n");
        return buf.toOwnedSlice();
    };
    defer dir.close();

    var iter = dir.iterate();
    while (iter.next() catch null) |file_entry| {
        if (file_entry.kind != .file) continue;
        if (!mem.endsWith(u8, file_entry.name, ".volt")) continue;

        // Read the file
        const file = dir.openFile(file_entry.name, .{}) catch continue;
        defer file.close();

        const content = file.readToEndAlloc(allocator, 1024 * 1024) catch continue;
        defer allocator.free(content);

        // Parse the .volt file
        var request = VoltFile.parse(allocator, content) catch continue;
        defer request.deinit();

        // Build doc entry
        var doc_entry = fromRequest(allocator, &request, file_entry.name) catch continue;
        entries.append(doc_entry) catch {
            for (doc_entry.tests.items) |t| {
                allocator.free(t);
            }
            doc_entry.deinit();
            continue;
        };
    }

    return generateMarkdown(allocator, entries.items, title);
}

// ── Tests ───────────────────────────────────────────────────────────────

test "generate markdown from doc entry" {
    var entry = DocEntry.init(std.testing.allocator);
    defer entry.deinit();
    entry.name = "get-users.volt";
    entry.method = "GET";
    entry.url = "/api/users";
    entry.body_type = "none";
    entry.auth_type = "bearer";

    try entry.headers.append(.{ .name = "Accept", .value = "application/json" });
    try entry.headers.append(.{ .name = "Authorization", .value = "Bearer token123" });
    try entry.tests.append("status equals 200");
    try entry.tests.append("body contains users");

    const doc_entries = [_]DocEntry{entry};
    const result = try generateMarkdown(std.testing.allocator, &doc_entries, "My API");
    defer std.testing.allocator.free(result);

    try std.testing.expect(mem.indexOf(u8, result, "# API Documentation: My API") != null);
    try std.testing.expect(mem.indexOf(u8, result, "## GET /api/users") != null);
    try std.testing.expect(mem.indexOf(u8, result, "get-users.volt") != null);
    try std.testing.expect(mem.indexOf(u8, result, "| Accept | application/json |") != null);
    try std.testing.expect(mem.indexOf(u8, result, "bearer") != null);
    try std.testing.expect(mem.indexOf(u8, result, "status equals 200") != null);
    try std.testing.expect(mem.indexOf(u8, result, "body contains users") != null);
}

test "fromRequest conversion" {
    var req = VoltFile.VoltRequest.init(std.testing.allocator);
    defer req.deinit();
    req.method = .POST;
    req.url = "https://api.example.com/users";
    req.body_type = .json;
    req.body = "{\"name\": \"test\"}";
    try req.addHeader("Content-Type", "application/json");
    try req.tests.append(.{ .field = "status", .operator = "equals", .value = "201" });

    var entry = try fromRequest(std.testing.allocator, &req, "create-user.volt");
    defer {
        std.testing.allocator.free(entry.name);
        std.testing.allocator.free(entry.url);
        if (entry.body_example) |b| std.testing.allocator.free(b);
        for (entry.headers.items) |h| {
            std.testing.allocator.free(h.name);
            std.testing.allocator.free(h.value);
        }
        for (entry.tests.items) |t| {
            std.testing.allocator.free(t);
        }
        entry.deinit();
    }

    try std.testing.expectEqualStrings("POST", entry.method);
    try std.testing.expectEqualStrings("https://api.example.com/users", entry.url);
    try std.testing.expectEqualStrings("create-user.volt", entry.name);
    try std.testing.expectEqualStrings("json", entry.body_type);
    try std.testing.expectEqualStrings("{\"name\": \"test\"}", entry.body_example.?);
    try std.testing.expectEqual(@as(usize, 1), entry.headers.items.len);
    try std.testing.expectEqualStrings("Content-Type", entry.headers.items[0].name);
    try std.testing.expectEqual(@as(usize, 1), entry.tests.items.len);
    try std.testing.expect(mem.indexOf(u8, entry.tests.items[0], "status equals 201") != null);
}
