const std = @import("std");
const mem = std.mem;
const Allocator = mem.Allocator;
const VoltFile = @import("volt_file.zig");

// ── Export Functionality ────────────────────────────────────────────────

/// Export a collection of .volt files to OpenAPI 3.0 YAML
pub fn exportOpenAPI(
    allocator: Allocator,
    requests: []const VoltFile.VoltRequest,
    collection_name: []const u8,
) ![]const u8 {
    var buf = std.ArrayList(u8).init(allocator);
    const writer = buf.writer();

    try writer.writeAll("openapi: '3.0.3'\n");
    try writer.writeAll("info:\n");
    try writer.print("  title: {s}\n", .{collection_name});
    try writer.writeAll("  version: '1.1.0'\n");
    try writer.writeAll("  description: Generated by Volt API Client\n");

    // Extract servers from URLs
    var servers = std.StringHashMap(void).init(allocator);
    defer servers.deinit();

    for (requests) |req| {
        const base = extractBaseUrl(req.url);
        if (base.len > 0) {
            servers.put(base, {}) catch |err| {
                std.debug.print("warning: exporter: server dedup put failed: {s}\n", .{@errorName(err)});
            };
        }
    }

    try writer.writeAll("servers:\n");
    var server_it = servers.iterator();
    while (server_it.next()) |entry| {
        try writer.print("  - url: {s}\n", .{entry.key_ptr.*});
    }

    // Paths -- group requests by path to avoid duplicate YAML keys
    var seen_paths = std.StringHashMap(void).init(allocator);
    defer seen_paths.deinit();

    try writer.writeAll("paths:\n");
    for (requests) |req| {
        const path = extractPath(req.url);
        const method_lower = methodToLower(req.method);

        // Only emit the path key once; subsequent methods go under the same path
        if (!seen_paths.contains(path)) {
            seen_paths.put(path, {}) catch |err| {
                std.debug.print("warning: exporter: path dedup put failed: {s}\n", .{@errorName(err)});
            };
            try writer.print("  {s}:\n", .{path});
        }
        try writer.print("    {s}:\n", .{method_lower});

        if (req.name) |name| {
            try writer.print("      summary: {s}\n", .{name});
            try writer.print("      operationId: {s}\n", .{sanitizeOperationId(name)});
        }

        // Request body
        if (req.body != null and req.body_type != .none) {
            try writer.writeAll("      requestBody:\n");
            try writer.writeAll("        required: true\n");
            try writer.writeAll("        content:\n");

            const content_type = switch (req.body_type) {
                .json => "application/json",
                .form => "application/x-www-form-urlencoded",
                .xml => "application/xml",
                .raw => "text/plain",
                .multipart => "multipart/form-data",
                .none => "application/octet-stream",
            };

            try writer.print("          {s}:\n", .{content_type});
            try writer.writeAll("            schema:\n");
            try writer.writeAll("              type: object\n");
        }

        // Responses
        try writer.writeAll("      responses:\n");
        try writer.writeAll("        '200':\n");
        try writer.writeAll("          description: Successful response\n");

        // Headers as parameters
        var has_params = false;
        for (req.headers.items) |h| {
            if (mem.eql(u8, h.name, "Content-Type")) continue;
            if (mem.eql(u8, h.name, "Accept")) continue;
            if (mem.eql(u8, h.name, "Authorization")) continue;

            if (!has_params) {
                try writer.writeAll("      parameters:\n");
                has_params = true;
            }
            try writer.print("        - name: {s}\n", .{h.name});
            try writer.writeAll("          in: header\n");
            try writer.writeAll("          schema:\n");
            try writer.writeAll("            type: string\n");
        }

        // Security
        if (req.auth.type != .none) {
            try writer.writeAll("      security:\n");
            switch (req.auth.type) {
                .bearer => try writer.writeAll("        - bearerAuth: []\n"),
                .basic => try writer.writeAll("        - basicAuth: []\n"),
                .api_key => try writer.writeAll("        - apiKeyAuth: []\n"),
                .digest => try writer.writeAll("        - digestAuth: []\n"),
                .aws, .hawk, .oauth_cc, .oauth_password, .oauth_implicit => {},
                .none => {},
            }
        }
    }

    // Security schemes
    try writer.writeAll("components:\n");
    try writer.writeAll("  securitySchemes:\n");
    try writer.writeAll("    bearerAuth:\n");
    try writer.writeAll("      type: http\n");
    try writer.writeAll("      scheme: bearer\n");
    try writer.writeAll("    basicAuth:\n");
    try writer.writeAll("      type: http\n");
    try writer.writeAll("      scheme: basic\n");
    try writer.writeAll("    apiKeyAuth:\n");
    try writer.writeAll("      type: apiKey\n");
    try writer.writeAll("      in: header\n");
    try writer.writeAll("      name: X-API-Key\n");
    try writer.writeAll("    digestAuth:\n");
    try writer.writeAll("      type: http\n");
    try writer.writeAll("      scheme: digest\n");

    return buf.toOwnedSlice();
}

/// Export a single .volt request as a curl command
pub fn exportCurl(request: *const VoltFile.VoltRequest, allocator: Allocator) ![]const u8 {
    var buf = std.ArrayList(u8).init(allocator);
    const writer = buf.writer();

    try writer.writeAll("curl");

    // Method
    if (request.method != .GET) {
        try writer.print(" -X {s}", .{request.method.toString()});
    }

    // URL
    try writer.print(" '{s}'", .{request.url});

    // Headers
    for (request.headers.items) |h| {
        try writer.print(" \\\n  -H '{s}: {s}'", .{ h.name, h.value });
    }

    // Auth
    switch (request.auth.type) {
        .bearer => {
            if (request.auth.token) |token| {
                try writer.print(" \\\n  -H 'Authorization: Bearer {s}'", .{token});
            }
        },
        .basic => {
            if (request.auth.username) |user| {
                if (request.auth.password) |pass| {
                    try writer.print(" \\\n  -u '{s}:{s}'", .{ user, pass });
                }
            }
        },
        .api_key => {
            if (request.auth.key_name) |name| {
                if (request.auth.key_value) |value| {
                    const location = request.auth.key_location orelse "header";
                    if (mem.eql(u8, location, "header")) {
                        try writer.print(" \\\n  -H '{s}: {s}'", .{ name, value });
                    }
                }
            }
        },
        .digest => {
            if (request.auth.username) |user| {
                if (request.auth.password) |pass| {
                    try writer.print(" \\\n  --digest -u '{s}:{s}'", .{ user, pass });
                }
            }
        },
        .aws, .hawk, .oauth_cc, .oauth_password, .oauth_implicit => {},
        .none => {},
    }

    // Body
    if (request.body) |body| {
        try writer.writeAll(" \\\n  -d '");
        // Escape single quotes in body
        for (body) |c| {
            if (c == '\'') {
                try writer.writeAll("'\\''");
            } else {
                try writer.writeByte(c);
            }
        }
        try writer.writeByte('\'');
    }

    try writer.writeByte('\n');
    return buf.toOwnedSlice();
}

/// Export a .volt request as Python requests code
pub fn exportPython(request: *const VoltFile.VoltRequest, allocator: Allocator) ![]const u8 {
    var buf = std.ArrayList(u8).init(allocator);
    const writer = buf.writer();

    try writer.writeAll("import requests\n\n");

    // Headers dict
    if (request.headers.items.len > 0) {
        try writer.writeAll("headers = {\n");
        for (request.headers.items) |h| {
            try writer.writeAll("    \"");
            try writeEscapedString(writer, h.name);
            try writer.writeAll("\": \"");
            try writeEscapedString(writer, h.value);
            try writer.writeAll("\",\n");
        }
        try writer.writeAll("}\n\n");
    }

    // Request call
    const method_lower = methodToLower(request.method);
    try writer.print("response = requests.{s}(\n", .{method_lower});
    try writer.writeAll("    \"");
    try writeEscapedString(writer, request.url);
    try writer.writeByte('"');

    if (request.headers.items.len > 0) {
        try writer.writeAll(",\n    headers=headers");
    }

    if (request.body) |body| {
        if (request.body_type == .json) {
            try writer.writeAll(",\n    json=");
            try writer.writeAll(body);
        } else {
            try writer.writeAll(",\n    data=\"\"\"");
            try writer.writeAll(body);
            try writer.writeAll("\"\"\"");
        }
    }

    try writer.writeAll(",\n)\n\n");
    try writer.writeAll("print(f\"Status: {response.status_code}\")\n");
    try writer.writeAll("print(response.text)\n");

    return buf.toOwnedSlice();
}

/// Export a .volt request as JavaScript fetch code
pub fn exportJavaScript(request: *const VoltFile.VoltRequest, allocator: Allocator) ![]const u8 {
    var buf = std.ArrayList(u8).init(allocator);
    const writer = buf.writer();

    try writer.writeAll("const response = await fetch(\"");
    try writeEscapedString(writer, request.url);
    try writer.writeAll("\", {\n");
    try writer.print("  method: \"{s}\",\n", .{request.method.toString()});

    if (request.headers.items.len > 0) {
        try writer.writeAll("  headers: {\n");
        for (request.headers.items) |h| {
            try writer.writeAll("    \"");
            try writeEscapedString(writer, h.name);
            try writer.writeAll("\": \"");
            try writeEscapedString(writer, h.value);
            try writer.writeAll("\",\n");
        }
        try writer.writeAll("  },\n");
    }

    if (request.body) |body| {
        try writer.writeAll("  body: JSON.stringify(");
        try writer.writeAll(body);
        try writer.writeAll("),\n");
    }

    try writer.writeAll("});\n\n");
    try writer.writeAll("const data = await response.json();\n");
    try writer.writeAll("console.log(data);\n");

    return buf.toOwnedSlice();
}

/// Export a .volt request as Go code
pub fn exportGo(request: *const VoltFile.VoltRequest, allocator: Allocator) ![]const u8 {
    var buf = std.ArrayList(u8).init(allocator);
    const writer = buf.writer();

    try writer.writeAll("package main\n\n");
    try writer.writeAll("import (\n");
    try writer.writeAll("    \"fmt\"\n");
    try writer.writeAll("    \"io\"\n");
    try writer.writeAll("    \"net/http\"\n");
    if (request.body != null) {
        try writer.writeAll("    \"strings\"\n");
    }
    try writer.writeAll(")\n\n");
    try writer.writeAll("func main() {\n");

    if (request.body) |body| {
        try writer.writeAll("    body := strings.NewReader(`");
        // Escape backticks in Go raw string literals
        for (body) |c| {
            if (c == '`') {
                try writer.writeAll("` + \"`\" + `");
            } else {
                try writer.writeByte(c);
            }
        }
        try writer.writeAll("`)\n");
        try writer.print("    req, err := http.NewRequest(\"{s}\", \"", .{request.method.toString()});
        try writeEscapedString(writer, request.url);
        try writer.writeAll("\", body)\n");
    } else {
        try writer.print("    req, err := http.NewRequest(\"{s}\", \"", .{request.method.toString()});
        try writeEscapedString(writer, request.url);
        try writer.writeAll("\", nil)\n");
    }

    try writer.writeAll("    if err != nil {\n");
    try writer.writeAll("        panic(err)\n");
    try writer.writeAll("    }\n\n");

    for (request.headers.items) |h| {
        try writer.writeAll("    req.Header.Set(\"");
        try writeEscapedString(writer, h.name);
        try writer.writeAll("\", \"");
        try writeEscapedString(writer, h.value);
        try writer.writeAll("\")\n");
    }

    try writer.writeAll("\n    resp, err := http.DefaultClient.Do(req)\n");
    try writer.writeAll("    if err != nil {\n");
    try writer.writeAll("        panic(err)\n");
    try writer.writeAll("    }\n");
    try writer.writeAll("    defer resp.Body.Close()\n\n");
    try writer.writeAll("    respBody, _ := io.ReadAll(resp.Body)\n");
    try writer.writeAll("    fmt.Printf(\"Status: %d\\n\", resp.StatusCode)\n");
    try writer.writeAll("    fmt.Println(string(respBody))\n");
    try writer.writeAll("}\n");

    return buf.toOwnedSlice();
}

/// Write a string with backslash/double-quote escaping for Python/JS/Go string literals.
fn writeEscapedString(writer: anytype, s: []const u8) !void {
    for (s) |c| {
        switch (c) {
            '\\' => try writer.writeAll("\\\\"),
            '"' => try writer.writeAll("\\\""),
            '\n' => try writer.writeAll("\\n"),
            '\r' => try writer.writeAll("\\r"),
            '\t' => try writer.writeAll("\\t"),
            else => try writer.writeByte(c),
        }
    }
}

// ── Helpers ─────────────────────────────────────────────────────────────

fn extractBaseUrl(url: []const u8) []const u8 {
    if (mem.indexOf(u8, url, "://")) |scheme_end| {
        const after_scheme = url[scheme_end + 3 ..];
        if (mem.indexOf(u8, after_scheme, "/")) |path_start| {
            return url[0 .. scheme_end + 3 + path_start];
        }
        return url;
    }
    return "";
}

fn extractPath(url: []const u8) []const u8 {
    if (mem.indexOf(u8, url, "://")) |scheme_end| {
        const after_scheme = url[scheme_end + 3 ..];
        if (mem.indexOf(u8, after_scheme, "/")) |path_start| {
            return after_scheme[path_start..];
        }
        return "/";
    }
    if (url.len > 0 and url[0] == '/') return url;
    return "/";
}

fn methodToLower(method: VoltFile.Method) []const u8 {
    return switch (method) {
        .GET => "get",
        .POST => "post",
        .PUT => "put",
        .PATCH => "patch",
        .DELETE => "delete",
        .HEAD => "head",
        .OPTIONS => "options",
    };
}

/// Convert a human-readable name to a camelCase operationId.
/// Only keeps alphanumeric characters; capitalizes first letter after a removed char.
fn sanitizeOperationId(name: []const u8) []const u8 {
    // Static buffer for sanitized output (OpenAPI operationIds are typically short)
    const S = struct {
        var buf: [256]u8 = undefined;
    };
    var out_len: usize = 0;
    var capitalize_next = false;

    for (name) |c| {
        if (std.ascii.isAlphanumeric(c)) {
            if (out_len < S.buf.len) {
                S.buf[out_len] = if (capitalize_next) std.ascii.toUpper(c) else c;
                out_len += 1;
                capitalize_next = false;
            }
        } else {
            // Non-alphanumeric separator → capitalize next letter
            if (out_len > 0) capitalize_next = true;
        }
    }

    return S.buf[0..out_len];
}

// ── Tests ───────────────────────────────────────────────────────────────

test "export curl" {
    var req = VoltFile.VoltRequest.init(std.testing.allocator);
    defer req.deinit();
    req.method = .GET;
    req.url = "https://api.example.com/users";
    try req.addHeader("Accept", "application/json");

    const result = try exportCurl(&req, std.testing.allocator);
    defer std.testing.allocator.free(result);

    try std.testing.expect(mem.indexOf(u8, result, "curl") != null);
    try std.testing.expect(mem.indexOf(u8, result, "https://api.example.com/users") != null);
    try std.testing.expect(mem.indexOf(u8, result, "Accept: application/json") != null);
}

test "export curl with post body" {
    var req = VoltFile.VoltRequest.init(std.testing.allocator);
    defer req.deinit();
    req.method = .POST;
    req.url = "https://api.example.com/users";
    req.body = "{\"name\": \"test\"}";

    const result = try exportCurl(&req, std.testing.allocator);
    defer std.testing.allocator.free(result);

    try std.testing.expect(mem.indexOf(u8, result, "-X POST") != null);
    try std.testing.expect(mem.indexOf(u8, result, "-d") != null);
}

test "extract base url" {
    try std.testing.expectEqualStrings("https://api.example.com", extractBaseUrl("https://api.example.com/users"));
}
